server:
  port: 8080
  #spring默认的context path
#  context-path: /springboot
#  session:
#    timeout:
spring:
  datasource:
    url: jdbc:mysql://us-cdbr-iron-east-05.cleardb.net/heroku_ef8b13d33be2d76?useSSL=false
    username: b4bbd900347931
    password: de0d5e10
    driver-class-username: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:/static/
  resources:
    static-locations: classpath:/static/
logging:
  level:
    com.cscd.shoppingau: debug
  file: log.log
mybatis:
  configuration:
    map-underscore-to-camel-case: true