server:
  port: 8080
  #spring默认的context path
#  context-path: /springboot
#  session:
#    timeout:
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop_au?useSSL=false
    username: root
    password: lqbaobao365
    driver-class-username: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:/static/
  resources:
    static-locations: classpath:/static/
logging:
  level:
    com.cscd.shoppingau: debug
  file: log.log
mybatis:
  configuration:
    map-underscore-to-camel-case: true